import { defineConfig } from 'vite';
import { resolve } from 'path';
import vue from '@vitejs/plugin-vue';
import tailwindcss from '@tailwindcss/vite';
import path from 'node:path';

export default defineConfig({
  plugins: [vue(), tailwindcss()], // to process SFC
  build: {
    lib: {
      entry: {
          main: resolve(__dirname, 'src/index.ts'),
          theme: resolve(__dirname, 'src/theme/index.ts'),
      },
      name: 'ui',
      formats: ['es', 'cjs'], // adding 'umd' requires globals set to every external module
      fileName: (format, entry) => `${entry}.${format}.js`,
    },
    rollupOptions: {
      // external modules won't be bundled into your library
      external: ['vue', /primevue\/.+/], // not every external has a global
      output: {
        // disable warning on src/index.ts using both default and named export
        exports: 'named',
        // Provide global variables to use in the UMD build
        // for externalized deps (not useful if 'umd' is not in lib.formats)
        globals: {
          vue: 'Vue',
        },
      },
    },
    emptyOutDir: false, // to retain the types folder generated by tsc
  },
  resolve: {
    alias: [
      { find: "@/", replacement: path.resolve(__dirname, "./src") }
    ],
  }
});
