import { defineConfig, mergeConfig } from 'vite';
import { resolve } from 'path';
import path from 'node:path';
import dts from 'vite-plugin-dts';


const config = defineConfig({
  build: {
    lib: {
      entry: {
          main: resolve(__dirname, 'src/index.ts'),
          theme: resolve(__dirname, 'src/theme/index.ts'),
      },
      name: 'ui',
      formats: ['es', 'cjs'], // adding 'umd' requires globals set to every external module
      fileName: (format, entry) => `${entry}.${format}.js`,
    },
    rollupOptions: {
      // external modules won't be bundled into your library
      external: ['vue', '**/*.cy.tsx'], // not every external has a global
      output: {
        // disable warning on src/index.ts using both default and named export
        exports: 'named',
        // Provide global variables to use in the UMD build
        // for externalized deps (not useful if 'umd' is not in lib.formats)
        globals: {
          vue: 'Vue',
        },
      },
    },
    emptyOutDir: false, // to retain the types folder generated by tsc
  },
  resolve: {
    alias: [
      { find: "@", replacement: path.resolve(__dirname, "./src") },
    ],
  }
});

export default async () => {
    const { default: tailwind } = await import('@tailwindcss/vite');
    const { default: vue} = await import('@vitejs/plugin-vue');

    return mergeConfig(config, {
        plugins: [
            tailwind(),
            vue(),
            dts({
                rollupTypes: true,
            })

        ],
    });
}
